# @package _global_
experiment: drqv2_dmc_pixel
device: cuda:0
seed: 1                 
num_train_steps: 500000
num_init_steps: 2000
test_every_steps: 5000
num_test_episodes: 10

env:
  env_id: cartpole_balance
  device: ${device}
  seed: ${seed}

encoder:
  name: TassaCnnEncoder
  feature_dim: 50

agent:
  name: DrQv2
  observation_space: ...
  action_space: ...
  device: ${device}
  feature_dim: ${encoder.feature_dim}
  lr: 0.0001
  eps: 0.00000001
  hidden_dim: 1024
  critic_target_tau: 0.01
  update_every_steps: 2
  network_init_method: orthogonal

storage:
  name: NStepReplayStorage
  storage_size: ${num_train_steps}
  batch_size: 256

distribution:
  name: TruncatedNormalNoise

augmentation:
  name: RandomShift