# @package _global_
experiment: ppo_bullet
device: cuda:0
seed: 1                 
num_train_steps: 1000000
num_steps: 2048
test_every_episodes: 10
num_test_episodes: 10

env:
  env_id: AntBulletEnv-v0
  num_envs: 1
  device: ${device}
  seed: ${seed}

encoder:
  name: IdentityEncoder
  feature_dim: 

agent:
  name: PPO
  observation_space: ...
  action_space: ...
  device: ${device}
  feature_dim: ${encoder.feature_dim}
  lr: 0.0003
  eps: 0.00001
  hidden_dim: 64
  clip_range: 0.2
  clip_range_vf: 
  n_epochs: 10
  vf_coef: 0.5
  ent_coef: 0.0
  aug_coef: 0.1
  max_grad_norm: 0.5
  network_init_method: orthogonal

storage:
  name: VanillaRolloutStorage
  batch_size: 64

distribution:
  name: DiagonalGaussian