# @package _global_
experiment: ppo_atari
device: cuda:0
seed: 1                 
num_train_steps: 10000000
num_steps: 128
test_every_episodes: 10
num_test_episodes: 10

env:
  env_id: PongNoFrameskip-v4
  num_envs: 8
  device: ${device}
  seed: ${seed}
  frame_stack: 4

encoder:
  name: MnihCnnEncoder
  feature_dim: 512

agent:
  name: PPO
  observation_space: ...
  action_space: ...
  device: ${device}
  feature_dim: ${encoder.feature_dim}
  lr: 0.00025
  eps: 0.00001
  hidden_dim: 512
  clip_range: 0.1
  clip_range_vf: 0.1
  n_epochs: 4
  vf_coef: 0.5
  ent_coef: 0.01
  aug_coef: 0.1
  max_grad_norm: 0.5
  network_init_method: orthogonal

storage:
  name: VanillaRolloutStorage
  batch_size: 256

distribution:
  name: Categorical