# @package _global_
experiment: sac_dmc_state
device: cuda:0
seed: 1                 
num_train_steps: 500000
num_init_steps: 2000
test_every_steps: 5000
num_test_episodes: 10

env:
  env_id: cartpole_balance
  device: ${device}
  seed: ${seed}
  visualize_reward: true
  from_pixels: false

encoder:
  name: IdentityEncoder
  feature_dim: 5

agent:
  name: SAC
  observation_space: ...
  action_space: ...
  device: ${device}
  feature_dim: ${encoder.feature_dim}
  lr: 0.0001
  eps: 0.00000001
  hidden_dim: 1024
  critic_target_tau: 0.005
  update_every_steps: 2
  log_std_range: [-5.0, 2]
  betas: [0.9, 0.999]
  temperature: 0.1
  fixed_temperature: false
  discount: 0.99
  network_init_method: orthogonal

storage:
  name: VanillaReplayStorage
  storage_size: ${num_train_steps}
  batch_size: 1024

distribution:
  name: SquashedNormal